### ISSUE TITLE
ページ左上の文字が重なる

### ISSUE THREAD

**Issue by hyper1FU** [shibu2sclub/yasarobo-hp#4]
ページ右上の "Yasarobo" と "2023" が重なります。

環境: Windows 10, Microsoft Edge Version 117.0.2045.47 (Official build) (64-bit)

![image](https://github.com/shibu2sclub/yasarobo-hp/assets/6614141/31ee48b6-12a0-4d33-9c2a-945c8ff833e4)

**Comment by hyper1FU** [comment]
ちょっと直しました。PR送ります

**Comment by makochan1209** [comment]
ごめんなさい多分出先で編集中に諦めて帰ったタイミングだと思います！
ブランチをdevelop切ってやっておくべきでした、こちらでも同じ対応してしまったので対応してもらったのに申し訳ない
PR送ってくれてありがとう！
